version: "3.8"
services:
  backend:
    build: .
    container_name: piano-backend
    ports:
      - "8080:8080" 
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/learn_piano?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    container_name: piano-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: learn_piano
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306" 

volumes:
  db_data:
